routes:

/ceo/:
  controller: channel
  filter: tag:[business,qbo_tips]

collections:
  /qbo-tips/:
    permalink: /qbo-tips/{slug}/
    template: index
    filter: primary_tag:qbo_tips
  /business/:
    permalink: /business/{slug}/
    template: index
    filter: primary_tag:business
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
