routes:

collections:
  /qbo-tips/:
    permalink: /qbo-tips/{slug}/
    template: index
    filter: tag:qbo_tips
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
